export { DriverCockpitSkeleton } from './DriverCockpitSkeleton';
export { ActiveDispatchSkeleton } from './ActiveDispatchSkeleton';
export { AmbulanceProfileSkeleton } from './AmbulanceProfileSkeleton';
export { DriverKycSkeleton } from './DriverKycSkeleton';
export { DriverSettingsSkeleton } from './DriverSettingsSkeleton';
export { ShiftHistorySkeleton } from './ShiftHistorySkeleton';
export { TrafficOptSkeleton } from './TrafficOptSkeleton';
export { DriverWalletSkeleton } from './DriverWalletSkeleton';
export { WardStatusSkeleton } from './WardStatusSkeleton';
