import { Applicant } from './types';

export const initialApplicants: Applicant[] = [
  {
    id: '#9821-V',
    name: 'Ariful Islam',
    avatarUrl: '/assets/dashboard/super-admin/ariful_applicant_avatar.png',
    urgency: 'Urgent',
    vehicleType: 'ICU Ambulance (DHA-129)',
    licensePlate: 'DHA-METRO-129-881',
    submittedAt: 'Submitted 2 hours ago',
    rawSubmittedDate: '12 Oct 2023, 14:32',
    driverId: 'PR-DRV-9022',
    division: 'Dhaka Metro North',
    phone: '+880 1712 882 110',
    licenseExpiry: '12 Jan 2029',
    status: 'Awaiting Verification',
    statusCategory: 'Pending',
    documents: {
      licenseFront: '/assets/dashboard/super-admin/license_front.png',
      licenseBack: '/assets/dashboard/super-admin/license_back.png',
      nidFront: '/assets/dashboard/super-admin/nid_front.png',
      nidBack: '/assets/dashboard/super-admin/nid_back.png',
      vehicleExterior: '/assets/dashboard/super-admin/ambulance_exterior.png',
      vehicleInterior: '/assets/dashboard/super-admin/ambulance_interior_icu.png',
      vehicleCabin: '/assets/dashboard/super-admin/ambulance_cabin.png',
    },
    timeline: [
      {
        title: 'Application Submitted',
        desc: 'Ariful Islam uploaded all mandatory documents via Driver App.',
        time: '12 Oct 2023, 14:32',
        status: 'INFO',
      },
      {
        title: 'Automated NID Validation',
        desc: 'System matched NID against Election Commission API database.',
        time: '12 Oct 2023, 14:35',
        status: 'SUCCESS',
      },
      {
        title: 'Administrative Review Started',
        desc: 'Assigned to Rahat Mahmud for manual document verification.',
        time: '12 Oct 2023, 16:40',
        status: 'IN_PROGRESS',
      },
    ],
  },
  {
    id: '#9818-V',
    name: 'Mustafizur Rahman',
    avatarUrl: '/assets/dashboard/super-admin/ariful_applicant_avatar.png',
    urgency: 'Standard',
    vehicleType: 'AC Ambulance (DHA-445)',
    licensePlate: 'DHA-METRO-445-092',
    submittedAt: 'Submitted 5 hours ago',
    rawSubmittedDate: '12 Oct 2023, 11:15',
    driverId: 'PR-DRV-9018',
    division: 'Dhaka Metro South',
    phone: '+880 1819 223 445',
    licenseExpiry: '04 Aug 2028',
    status: 'Awaiting Verification',
    statusCategory: 'Pending',
    documents: {
      licenseFront: '/assets/dashboard/super-admin/license_front.png',
      licenseBack: '/assets/dashboard/super-admin/license_back.png',
      nidFront: '/assets/dashboard/super-admin/nid_front.png',
      nidBack: '/assets/dashboard/super-admin/nid_back.png',
      vehicleExterior: '/assets/dashboard/super-admin/ambulance_exterior.png',
      vehicleInterior: '/assets/dashboard/super-admin/ambulance_interior_icu.png',
      vehicleCabin: '/assets/dashboard/super-admin/ambulance_cabin.png',
    },
    timeline: [
      {
        title: 'Application Submitted',
        desc: 'Mustafizur Rahman uploaded all mandatory documents via Driver App.',
        time: '12 Oct 2023, 11:15',
        status: 'INFO',
      },
      {
        title: 'Automated NID Validation',
        desc: 'System matched NID against Election Commission API database.',
        time: '12 Oct 2023, 11:18',
        status: 'SUCCESS',
      },
    ],
  },
  {
    id: '#9815-V',
    name: 'Salma Khatun',
    avatarUrl: '/assets/dashboard/patient/rashida-khatun.png',
    urgency: 'Standard',
    vehicleType: 'BLS Unit (DHA-882)',
    licensePlate: 'DHA-METRO-882-114',
    submittedAt: 'Submitted Yesterday',
    rawSubmittedDate: '11 Oct 2023, 16:20',
    driverId: 'PR-DRV-9015',
    division: 'Uttara Central',
    phone: '+880 1912 776 543',
    licenseExpiry: '19 Mar 2027',
    status: 'Awaiting Verification',
    statusCategory: 'Pending',
    documents: {
      licenseFront: '/assets/dashboard/super-admin/license_front.png',
      licenseBack: '/assets/dashboard/super-admin/license_back.png',
      nidFront: '/assets/dashboard/super-admin/nid_front.png',
      nidBack: '/assets/dashboard/super-admin/nid_back.png',
      vehicleExterior: '/assets/dashboard/super-admin/ambulance_exterior.png',
      vehicleInterior: '/assets/dashboard/super-admin/ambulance_interior_icu.png',
      vehicleCabin: '/assets/dashboard/super-admin/ambulance_cabin.png',
    },
    timeline: [
      {
        title: 'Application Submitted',
        desc: 'Salma Khatun uploaded all mandatory documents via Driver App.',
        time: '11 Oct 2023, 16:20',
        status: 'INFO',
      },
      {
        title: 'Automated NID Validation',
        desc: 'System matched NID against Election Commission API database.',
        time: '11 Oct 2023, 16:22',
        status: 'SUCCESS',
      },
    ],
  },
  {
    id: '#9810-V',
    name: 'Kabir Ahmed',
    avatarUrl: '/assets/dashboard/super-admin/ariful_applicant_avatar.png',
    urgency: 'Standard',
    vehicleType: 'Cardiac Unit (DHA-331)',
    licensePlate: 'DHA-METRO-331-550',
    submittedAt: 'Submitted Yesterday',
    rawSubmittedDate: '11 Oct 2023, 14:05',
    driverId: 'PR-DRV-9010',
    division: 'Mirpur Zone 2',
    phone: '+880 1611 998 012',
    licenseExpiry: '27 Nov 2029',
    status: 'Awaiting Verification',
    statusCategory: 'Pending',
    documents: {
      licenseFront: '/assets/dashboard/super-admin/license_front.png',
      licenseBack: '/assets/dashboard/super-admin/license_back.png',
      nidFront: '/assets/dashboard/super-admin/nid_front.png',
      nidBack: '/assets/dashboard/super-admin/nid_back.png',
      vehicleExterior: '/assets/dashboard/super-admin/ambulance_exterior.png',
      vehicleInterior: '/assets/dashboard/super-admin/ambulance_interior_icu.png',
      vehicleCabin: '/assets/dashboard/super-admin/ambulance_cabin.png',
    },
    timeline: [
      {
        title: 'Application Submitted',
        desc: 'Kabir Ahmed uploaded all mandatory documents via Driver App.',
        time: '11 Oct 2023, 14:05',
        status: 'INFO',
      },
      {
        title: 'Automated NID Validation',
        desc: 'System matched NID against Election Commission API database.',
        time: '11 Oct 2023, 14:08',
        status: 'SUCCESS',
      },
    ],
  },
];

